---
title: We need a better title
subtitle: Patterns and Trends in Environmental Data
author: Lucia Scheele and Laura Vetter
format:
  html:
    code-fold: true # makes the code in the output collapsable
execute:
  warning: false # hides warnings from the generated output
  message: false        # hides messages from the generated output
lang: en  # switch to "de" if you write your report in german
bibliography: bibliography.bib
---

```{r preprocessing}
#| code-summary: preprocessing
``` 

```{r preprocessing}
install.packages("pacman") 
library("pacman")
p_install_gh("benmarwick/wordcountaddin")
wordcountaddin::word_count("index.qmd")

``` 

## Abstract

## Introduction

@laube2011 investigate how temporal scale affects the calculation of movement parameters (speed, sinuosity and turning angle) of animal trajectories. 

## Material and Methods

## Results

## Discussion

## Appendix

### Wordcount

<!-- after installing the wordcountadding, remove the line "#| eval: false" -->

```{r}
#| eval: false
wordcountaddin::word_count("index.qmd")
```


